export const SET_SELLER = 'SET_SELLER'
export const SET_FOOD = 'SET_FOOD'
export const ADD_FOOD_COUNT = 'ADD_FOOD_COUNT'
export const MINUS_FOOD_COUNT = 'SET_FOOD_COUNT'
export const ADD_FOOD_ITEM = 'ADD_FOOD_ITEM'
export const CLEAR_SELLER_CART = 'CLEAR_SELLER_CART'
